### PR TITLE
the worst star function ever

### PR DESCRIPTION
**Pull request by ponchieponcho**
👀 @ellenkramp @rfpoulos Super lazy function but it works...with only 1,2,3,4,5

### CODE REVIEW

**Comment by ponchieponcho** [comment]
Once Rachel is done with the rating number, I should be able to pull that in....somehow

**Comment by ellenkramp** [comment]
cool, well as far as the start-generating function, I think you're good to go. ✅

**Comment by ponchieponcho** [comment]
I forgot to switch off of the branch when I went into styling mode. This is what the mobile looks like atm:
screen shot 2018-03-12 at 7 02 50 pm

**Comment by rfpoulos** [comment]
crazy code, but I'll take it.  looks amazing.  okay to merge.

**Comment by rfpoulos** [comment]
looked at merge conflict.  mostly cosmetic and an accidental duplication of the firebase initialization script.

**Comment by ponchieponcho** [comment]
@rfpoulos @ellenkramp Didn't have a merge conflict when I left yesterday but I guess that changed. Adjusted the files. Please confirm OK to merge.

**Comment by rfpoulos** [comment]
Okay to merge!

**Pull request merged**
